global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'host.docker.internal:9093'

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'sit223-production'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'host.docker.internal:3002'